/*
  # Create Products Table for Luxury Art Store

  1. New Tables
    - `products`
      - `id` (bigint, primary key, auto-increment)
      - `created_at` (timestamptz, default now)
      - `title` (text, required) - Product name
      - `description` (text, optional) - Detailed product description
      - `price` (numeric, required) - Product price
      - `images` (text[], required) - Array of image URLs
      - `shopier_url` (text, required) - Purchase link
      - `dimensions` (text, optional) - Physical dimensions (e.g., "30x40 cm")
      - `is_featured` (boolean, default false) - Featured product flag
      - `stock` (integer, default 1) - Available stock count

  2. Security
    - Enable RLS on `products` table
    - Add policy for public read access (anyone can view products)
    - Add policy for authenticated admin operations (insert, update, delete)

  3. Notes
    - Images are stored as URLs in an array for multiple product photos
    - Products are publicly viewable for the storefront
    - Stock tracking included for inventory management
*/

CREATE TABLE IF NOT EXISTS products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  title text NOT NULL,
  description text,
  price numeric NOT NULL,
  images text[] NOT NULL,
  shopier_url text NOT NULL,
  dimensions text,
  is_featured boolean DEFAULT false,
  stock integer DEFAULT 1
);

ALTER TABLE products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view products"
  ON products
  FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Authenticated users can insert products"
  ON products
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update products"
  ON products
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authenticated users can delete products"
  ON products
  FOR DELETE
  TO authenticated
  USING (true);